export enum ViewPage {
  PRODUCTS = "PRODUCTS",
  PRODUCT_DETAIL = "PRODUCT_DETAIL",
  BLOGS = "BLOGS",
  BLOGS_DETAIL = "BLOGS_DETAIL",
  HOMEPAGE = "HOMEPAGE",
  DOCUMENTATION = "DOCUMENTATION",
  DOCUMENTATION_DETAIL = "DOCUMENTATION_DETAIL",
  WHITE_MORTAL_SOLUTION = "WHITE_MORTAL_SOLUTION",
  SOLUTION_COLOR_GROUT = "SOLUTION_COLOR_GROUT",
  WATERPROOF_SOLUTION = "WATERPROOF_SOLUTION",
  SOLUTION_SPC = "SOLUTION_SPC",
}
